### ISSUE TITLE
Action fails on plans with no changes

### ISSUE THREAD

**Issue by stevie-** [liatrio/terraform-change-pr-commenter#30]
If we pass a plan with no changes to this action we get an error.

```
Run liatrio/terraform-change-pr-commenter@v1.3.1
  with:
    json-file: /home/runner/work/terragrunt-action/terragrunt-action/examples/test-pr-comment-terragrunt-no-change/test-no-change/tfplan.json
  
    github-token: ***
    expand-comment: false
  env:
    TERRAFORM_VERSION: 1.1.9
    TERRAGRUNT_VERSION: 0.37.1
Found PR # 7 from workflow context - proceeding to comment.
Error: resource_changes is not iterable
```

We can reproduce it with an empty `main.tf`: 
https://github.com/datadrivers/terragrunt-action/runs/6811210907?check_suite_focus=true#step:3:243

**Comment by RobertKelly** [comment]
Thanks for reporting.  Must have escaped the last refactor test scenario.  We'll get this corrected.

**Comment by stevie-** [comment]
thank you, works now
https://github.com/datadrivers/terragrunt-action/pull/8
