### ISSUE TITLE
bump nodejs to version 20

### ISSUE THREAD

**Issue by NissesSenap** [liatrio/terraform-change-pr-commenter#48]
Hi
First, thanks for your great GHA.

GitHub recently started pushing for the deprecation of nodejs 16, and currently using the GHA gives the following warning.

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: liatrio/terraform-change-pr-commenter@v1.4.1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

It would be great if this could be fixed and a new release cut.

Thanks in advance.

**Comment by RobertKelly** [comment]
Absolutely! We'll take care of it!

**Comment by RobertKelly** [comment]
@NissesSenap It should be good to go! Thanks!

**Comment by stevie-** [comment]
Thanks for the updates.
But action.yml still points to node16
https://github.com/liatrio/terraform-change-pr-commenter/blob/main/action.yml#L24
