### ISSUE TITLE
Feature contribution

### ISSUE THREAD

**Issue by someshkoli** [liatrio/terraform-change-pr-commenter#59]
Hey, 
I had some requirements to current setup, also saw that there are some pending issues to this. Have made these improvements in my fork and have published it for testing purposes.  
Here's the PR for it, see if we can get it onboarded here. Will be using my version till then. Cheers :clinking_glasses: 
https://github.com/liatrio/terraform-change-pr-commenter/pull/58

**Comment by jburns24** [comment]
Closing this issue because #58 was closed in favor of #60 which is merged.
