### ISSUE TITLE
Feature Request: Silence `changed_resources`console output

### ISSUE THREAD

**Issue by stevie-** [liatrio/terraform-change-pr-commenter#64]
On big tf-plans this actions outputs all changes in a json like format into github action workflow (log).

This is not helpful for non-debugging runs and makes it hard to find the TF plan inside it.

Can this [output](https://github.com/liatrio/terraform-change-pr-commenter/blob/main/dist/index.js#L12849) be configurable?
```
console.log("changed_resources", changed_resources)
```
So we are able to disable it.

**Comment by RobertKelly** [comment]
We'll take a look. I assume making this configurable is fairly simple.

**Comment by jburns24** [comment]
@stevie- Check out [v1.7.0](https://github.com/liatrio/terraform-change-pr-commenter/releases/tag/v1.7.0). We added an optional parameter `log-changed-resources` that will allow you to disable this logging 

https://github.com/liatrio/terraform-change-pr-commenter?tab=readme-ov-file#log-changed-resources

**Comment by stevie-** [comment]
Thanks, works that json output is not visible anymore.
Still shows what it will add to the PR comment, which feels like debug to me :)

And the new minimize feature works, but maybe not as expected.

If I have multiple jobs running, creating multiple pr-comments on it's own. all PR comments are minimized. But these PR comments were the first for each job.

Example: https://github.com/datadrivers/terragrunt-action/pull/36

**Comment by stevie-** [comment]
Use cases are 
workflows with multiple deployments or matrix usage.
