### ISSUE TITLE
Incorrect "No Changes" Comment in TF Plan with Imports but No Other Actions

### ISSUE THREAD

**Issue by comozo** [liatrio/terraform-change-pr-commenter#77]
Hello, 

We've discovered an edge case worth addressing. In a TF plan with no changes—meaning no updates, deletes, or creations—but with an import, the action will incorrectly comment "no changes." 

For instance:
 ```
Plan: 8 to import, 0 to add, 0 to change, 0 to destroy
```
![image](https://github.com/user-attachments/assets/3fa227bc-3e36-45ea-a871-d39729d0f99f)

**Comment by RobertKelly** [comment]
Thanks for bringing this to light. We will look at addressing it promptly.

**Comment by comozo** [comment]
Hey sorry it was mistake please discard. Sorry.
